### ISSUE TITLE
Vérifier le schéma de données

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/harvest-pubmed#1]
En fin de parsing, il faudrait ajouter une étape de vérification de schéma de données. 
Idéalement, le même système (avec le même schéma) devrait etre mis en place pour tous les harvester-parser, y compris dans "parser_html"

**Comment by annelhote** [comment]
https://python-jsonschema.readthedocs.io/en/stable/

**Comment by annelhote** [comment]
https://json-schema.org/understanding-json-schema/reference/
