### ISSUE TITLE
Ajout d'une route qui enchaîne harvesting et parsing pour un range de dates

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/harvest-pubmed#2]

**Comment by annelhote** [comment]
Pour répondre à ce besoin tout en préservant une certaine modularité, j'ai :
- Renommé l'argument de la requête "type" en "task"
- Ajouté une nouvelle task nommée "all" qui enchaîne le harvesting puis le parsing pour une date donnée
- Ajouté le endpoint "/pubmed_interval" qui prend les arguments "start" et "end" en plus de l'argument "task", puis itère sur chaque date comprise entre start et end (inclues) pour exécuter la task demandée
